FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y telnetd netcat openssl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -m -p $(openssl passwd -1 1234) test

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]

